import { validateJobCommand, validateJobEvent } from '../contracts/job.js';
import type { JobEvent, JobIdentity } from '../contracts/job.js';
import type { JobStoreResult } from './job-store.js';

/** Trusted server data only. Never expose owner tokens or fences to a model/client. */
export interface JobLeaseAuthority {
  readonly host: JobIdentity['host'];
  readonly grantRevision: number;
  readonly cancellationRevision: number;
}
export interface JobLeaseFence extends JobLeaseAuthority {
  readonly identity: JobIdentity;
  readonly ownerToken: string;
  readonly epoch: number;
  /** Host-clock milliseconds. Informational: storage checks its current expiry. */
  readonly expiresAt: number;
}
export type JobLeaseOperation = 'claim' | 'renew' | 'release' | 'check' | 'append' | 'complete' | 'admit_effect';
export interface JobLeaseHost {
  /** Authenticate and authorize this exact original identity and operation anew.
   * Deny cancelled/held/revoked work with not_authorized. Hold native authority
   * stable until run AND its transaction commit finish (native lock/transaction).
   * Invoke run once, awaited, only on authorization. A check followed by an
   * unprotected callback does not implement this contract. Never trust ID possession.
   */
  withAuthority<T>(identity: JobIdentity, operation: JobLeaseOperation,
    run: (authority: JobLeaseAuthority) => Promise<JobStoreResult<T>>): Promise<JobStoreResult<T>>;
  /** Trusted, nondecreasing safe integer milliseconds, shared across owners. */
  now(): number;
  /** Unique opaque owner token per attempt, generated by the trusted host. */
  newOwnerToken(): string;
}
/** Storage is trusted infrastructure; this context is supplied only inside the
 * host's authority critical section, never deserialized from a caller. */
export interface JobLeaseContext {
  readonly authority: JobLeaseAuthority;
  readonly now: () => number;
}
export interface JobAppendFence extends JobLeaseContext { readonly fence: JobLeaseFence }
export type JobAppendResult = { readonly event: JobEvent; readonly replayed: boolean };
export interface JobLeaseStore {
  claim(identity: JobIdentity, ownerToken: string, ttlMs: number, context: JobLeaseContext): Promise<JobStoreResult<JobLeaseFence | null>>;
  renew(fence: JobLeaseFence, ttlMs: number, context: JobLeaseContext): Promise<JobStoreResult<JobLeaseFence>>;
  release(fence: JobLeaseFence, context: JobLeaseContext): Promise<JobStoreResult<void>>;
  check(fence: JobLeaseFence, context: JobLeaseContext): Promise<JobStoreResult<JobLeaseFence>>;
  append(event: JobEvent, context: JobAppendFence, complete: boolean, effectAdmission?: boolean): Promise<JobStoreResult<JobAppendResult>>;
}
export interface JobLease {
  claim(identity: JobIdentity, ttlMs: number): Promise<JobStoreResult<JobLeaseFence | null>>;
  renew(fence: JobLeaseFence, ttlMs: number): Promise<JobStoreResult<JobLeaseFence>>;
  release(fence: JobLeaseFence): Promise<JobStoreResult<void>>;
  /** Immediately before execution/output release; not a reusable execution grant.
   * Cannot undo transmission or authorize replay of an unknown effect. */
  check(fence: JobLeaseFence): Promise<JobStoreResult<JobLeaseFence>>;
  append(event: JobEvent, fence: JobLeaseFence): Promise<JobStoreResult<JobAppendResult>>;
  /** Commit an unknown effect before dispatch. Only a new admission may trigger
   * the external call; a replay must reconcile the original effect instead. */
  admitEffect(event: JobEvent, fence: JobLeaseFence): Promise<JobStoreResult<JobAppendResult>>;
  /** Atomically append a terminal event and release ownership. */
  complete(event: JobEvent, fence: JobLeaseFence): Promise<JobStoreResult<JobAppendResult>>;
}

const ref = (v: unknown): v is string => typeof v === 'string' && /^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(v);
const natural = (v: unknown): v is number => typeof v === 'number' && Number.isSafeInteger(v) && v >= 0;
const positive = (v: unknown): v is number => natural(v) && v > 0;
function exact(v: any, keys: string[]): boolean {
  if (!v || typeof v !== 'object' || ![Object.prototype, null].includes(Object.getPrototypeOf(v))) return false;
  return Reflect.ownKeys(v).length === keys.length && keys.every(k => {
    const d = Object.getOwnPropertyDescriptor(v, k); return d?.enumerable && 'value' in d;
  });
}
/** Internal helpers shared with trusted reference storage, not package exports. */
export function sameLeaseValue(a: any, b: any): boolean {
  if (a === b) return true;
  return !!a && !!b && typeof a === 'object' && typeof b === 'object'
    && Object.keys(a).length === Object.keys(b).length
    && Object.keys(a).every(k => Object.hasOwn(b, k) && sameLeaseValue(a[k], b[k]));
}
export function validLeaseAuthority(a: JobLeaseAuthority, identity: JobIdentity): boolean {
  return exact(a, ['host', 'grantRevision', 'cancellationRevision']) && positive(a.grantRevision)
    && natural(a.cancellationRevision)
    && validateJobCommand({ command: 'inspect', identity: { ...identity, host: a.host } }).ok
    && sameLeaseValue(a.host, identity.host);
}
export function validJobFence(f: JobLeaseFence): boolean {
  return exact(f, ['identity', 'host', 'grantRevision', 'cancellationRevision', 'ownerToken', 'epoch', 'expiresAt'])
    && validateJobCommand({ command: 'inspect', identity: f.identity }).ok
    && validLeaseAuthority({ host: f.host, grantRevision: f.grantRevision, cancellationRevision: f.cancellationRevision }, f.identity)
    && ref(f.ownerToken) && positive(f.epoch) && natural(f.expiresAt);
}
function copy<T>(v: T): T { return JSON.parse(JSON.stringify(v)) as T; }

/** Construction/import performs no IO. Native Handrail ownership remains external. */
export function createJobLease(host: JobLeaseHost, store: JobLeaseStore): JobLease {
  async function authorized<T>(identity: JobIdentity, operation: JobLeaseOperation,
    run: (context: JobLeaseContext) => Promise<JobStoreResult<T>>): Promise<JobStoreResult<T>> {
    try {
      return await host.withAuthority(copy(identity), operation, async authority => {
        try {
          if (!validLeaseAuthority(authority, identity)) return { ok: false, code: 'not_authorized' };
          const context = { authority: copy(authority), now: () => {
            const now = host.now(); if (!natural(now)) throw new Error(); return now;
          } };
          return await run(context);
        } catch { return { ok: false, code: 'unavailable' }; }
      });
    } catch { return { ok: false, code: 'not_authorized' }; }
  }
  function fenced<T>(input: JobLeaseFence, operation: JobLeaseOperation,
    run: (fence: JobLeaseFence, context: JobLeaseContext) => Promise<JobStoreResult<T>>): Promise<JobStoreResult<T>> {
    try {
      if (!validJobFence(input)) return Promise.resolve({ ok: false, code: 'invalid_payload' });
      const fence = copy(input);
      return authorized(fence.identity, operation, context => {
        if (!sameLeaseValue(context.authority, { host: fence.host, grantRevision: fence.grantRevision,
          cancellationRevision: fence.cancellationRevision })) return Promise.resolve({ ok: false, code: 'lease_lost' });
        return run(fence, context);
      });
    } catch { return Promise.resolve({ ok: false, code: 'invalid_payload' }); }
  }
  function append(input: JobEvent, fence: JobLeaseFence, complete: boolean, effect = false): Promise<JobStoreResult<JobAppendResult>> {
    try {
      if (!validateJobEvent(input).ok || input.kind === 'submitted'
        || (effect && (input.kind !== 'effects_recorded' || !input.snapshot.effects.some(item => item.outcome === 'unknown')))
        || (complete && !['succeeded', 'failed', 'cancelled'].includes(input.kind))) return Promise.resolve({ ok: false, code: 'invalid_payload' });
      const event = copy(input);
      return fenced(fence, effect ? 'admit_effect' : complete ? 'complete' : 'append', (f, context) => {
        if (!sameLeaseValue(event.snapshot.identity, f.identity)) return Promise.resolve({ ok: false, code: 'identity_mismatch' });
        return store.append(event, { ...context, fence: f }, complete, effect);
      });
    } catch { return Promise.resolve({ ok: false, code: 'invalid_payload' }); }
  }
  return {
    claim(input, ttlMs) {
      try {
        if (!validateJobCommand({ command: 'inspect', identity: input }).ok || !positive(ttlMs)) return Promise.resolve({ ok: false, code: 'invalid_payload' });
        const identity = copy(input);
        return authorized(identity, 'claim', context => {
          const token = host.newOwnerToken();
          if (!ref(token)) return Promise.resolve({ ok: false, code: 'not_authorized' });
          return store.claim(identity, token, ttlMs, context);
        });
      } catch { return Promise.resolve({ ok: false, code: 'invalid_payload' }); }
    },
    renew(fence, ttlMs) {
      if (!positive(ttlMs)) return Promise.resolve({ ok: false, code: 'invalid_payload' });
      return fenced(fence, 'renew', (f, context) => store.renew(f, ttlMs, context));
    },
    release: fence => fenced(fence, 'release', (f, context) => store.release(f, context)),
    check: fence => fenced(fence, 'check', (f, context) => store.check(f, context)),
    append: (event, fence) => append(event, fence, false),
    admitEffect: (event, fence) => append(event, fence, false, true),
    complete: (event, fence) => append(event, fence, true),
  };
}
